<?php

/***************************************************
 * ログイン画面
 *
 *
 * @package
 * @access  public
 * @author  
 * @create  
 * @version 
 ***************************************************/

require_once('base_model_sample_back_base.inc');
require_once('conv_util.inc');

class login extends base_model_sample_back_base {



//処理
public function execute() {
//print "Trap 1\n";
}

} // end of class

