<?php

/***************************************************
 * ログイン後トップ画面
 *
 *
 * @package
 * @access  public
 * @author  
 * @create  
 * @version 
 ***************************************************/

require_once('base_model_sample_back_base.inc');
//require_once('conv_util.inc');

class top extends base_model_sample_back_base {

//処理
public function execute_auth() {
//print "Trap 1\n";

//print 'id is ' . $this->get_id() . "<br>\n";

  //
  return ;
}

} // end of class

